# Generated by Django 4.0.2 on 2022-02-21 15:13

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arkogroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('password', models.CharField(max_length=200)),
                ('key', models.CharField(blank=True, max_length=200, null=True)),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name='Arkouser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('arkogroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arko.arkogroup')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=40)),
                ('sort_no', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('arkogroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arko.arkogroup')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=40)),
                ('sort_no', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arko.block')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=40)),
                ('sort_no', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('is_ban', models.BooleanField(default=False)),
                ('disable', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arko.arkogroup')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NoName', max_length=40)),
                ('sort_no', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arko.card')),
                ('stat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arko.status')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_stat', models.CharField(max_length=40)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arko.room')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arko.arkouser')),
            ],
        ),
    ]
