# Generated by Django 4.0.1 on 2022-02-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arko', '0002_arkogroup_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
