# Generated by Django 4.0.1 on 2022-02-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arko', '0004_remove_block_group_block_arkogroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='is_active',
        ),
        migrations.AddField(
            model_name='card',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='is_ban',
            field=models.BooleanField(default=False),
        ),
    ]
