# Generated by Django 4.0.1 on 2022-02-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arko', '0005_remove_status_is_active_card_address_status_is_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='NoName', max_length=40),
        ),
    ]
