# Generated by Django 4.0.1 on 2022-02-11 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arko', '0007_alter_status_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arko.status'),
        ),
    ]
