# Generated by Django 4.0.1 on 2022-02-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arko', '0009_alter_history_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
