# Generated by Django 4.0.1 on 2022-02-04 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arko', '0003_block_comment_alter_card_comment_alter_room_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='group',
        ),
        migrations.AddField(
            model_name='block',
            name='arkogroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arko.arkogroup'),
        ),
    ]
